# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
    node: circleci/node@4.7

jobs:
    build:
        resource_class: small
        docker:
            - image: cimg/node:16.15
        steps:
            - checkout
            - run: yarn install
            - run: yarn ensure-version
            - run: yarn lint
            - run: yarn build
    publish:
        resource_class: small
        docker:
            - image: cimg/node:16.15
        steps:
            - checkout
            - run: yarn install
            - run: yarn ensure-version
            - run: yarn build
            - run:
                  command: |
                      npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                      yarn publish --non-interactive

# Invoke jobs via workflows
workflows:
    build_engine:
        jobs:
            - build:
                  filters:
                      branches:
                          ignore: main
    publish_engine:
        jobs:
            - publish:
                  filters:
                      branches:
                          only: main
